const GEMINI_API_KEY = "YOUR_GEMINI_API_KEY";
// ==============================
// DOM ELEMENTS
// ==============================

const form = document.getElementById("coverLetterForm");
const output = document.getElementById("output");
const loading = document.getElementById("loading");
const copyBtn = document.getElementById("copyBtn");
const resumeInput = document.getElementById("resume");
const fileName = document.getElementById("fileName");
const clearBtn = document.getElementById("clearBtn");

// ==============================
// DISPLAY SELECTED PDF NAME
// ==============================

resumeInput.addEventListener("change", () => {
    if (resumeInput.files.length > 0) {
        fileName.textContent = resumeInput.files[0].name;
    } else {
        fileName.textContent = "No file selected";
    }
});

// ==============================
// GENERATE COVER LETTER
// ==============================

form.addEventListener("submit", function (e) {

    e.preventDefault();

    const name = document.getElementById("name").value.trim();
    const role = document.getElementById("role").value.trim();
    const company = document.getElementById("company").value.trim();
    const skills = document.getElementById("skills").value.trim();

    if (!name || !role || !company || !skills) {
        alert("Please fill in all required fields.");
        return;
    }

    loading.classList.remove("hidden");

    output.innerHTML = "";

    setTimeout(() => {

        const letter = `Dear Hiring Manager,

I am writing to express my strong interest in the ${role} position at ${company}.

My name is ${name}, and I possess practical knowledge in ${skills}. I am passionate about solving real-world problems, learning new technologies, and delivering high-quality work.

I believe my technical skills, dedication, and eagerness to grow make me a valuable candidate for your team. I am excited about the opportunity to contribute to ${company} while continuing to develop professionally.

Thank you for considering my application. I look forward to the opportunity to discuss how my skills and enthusiasm align with your organization's goals.

Sincerely,

${name}`;

        loading.classList.add("hidden");

        output.textContent = letter;

    }, 1800);

});

// ==============================
// COPY TO CLIPBOARD
// ==============================

copyBtn.addEventListener("click", () => {

    const text = output.textContent.trim();

    if (text === "" || text.includes("appear here")) {
        alert("Generate a cover letter first.");
        return;
    }

    navigator.clipboard.writeText(text);

    copyBtn.textContent = "Copied!";

    setTimeout(() => {
        copyBtn.textContent = "Copy";
    }, 2000);

});

// ==============================
// CLEAR FORM
// ==============================

clearBtn.addEventListener("click", () => {

    output.innerHTML = `
        <p class="placeholder">
            Your AI-generated cover letter will appear here.
        </p>
    `;

    fileName.textContent = "No file selected";

    loading.classList.add("hidden");

});

const downloadBtn = document.getElementById("downloadPdfBtn");

downloadBtn.addEventListener("click", () => {

    const text = output.textContent.trim();

    if (text === "" || text.includes("appear here")) {
        alert("Generate a cover letter first.");
        return;
    }

    const { jsPDF } = window.jspdf;

    const doc = new jsPDF("p", "mm", "a4");

    const pageWidth = doc.internal.pageSize.getWidth();

    const margin = 20;
    let y = 20;

    // ===== Title =====
    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.text("COVER LETTER", pageWidth / 2, y, { align: "center" });

    y += 10;

    doc.setDrawColor(100);
    doc.line(margin, y, pageWidth - margin, y);

    y += 10;

    // ===== Candidate Information =====
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    const candidateName = document.getElementById("name").value;
    const jobRole = document.getElementById("role").value;
    const targetCompany = document.getElementById("company").value;
    doc.text(`Candidate : ${candidateName}`, margin, y);
    y += 7;

    doc.text(`Role      : ${jobRole}`, margin, y);
    y += 7;

    doc.text(`Company   : ${targetCompany}`, margin, y);
    y +=7 

    doc.line(margin, y, pageWidth - margin, y);

    y += 10;

    // ===== Cover Letter =====
    doc.setFont("times", "normal");
    doc.setFontSize(12);

    const lines = doc.splitTextToSize(
        text,
        pageWidth - margin * 2
    );

    doc.text(lines, margin, y);

    // ===== Footer =====
    doc.setFont("helvetica", "italic");
    doc.setFontSize(10);

    doc.text(
        "Generated By AI Cover Letter Generator",
        pageWidth / 2,
        250,
        { align: "center" }
    );

    doc.text(
        "Powered By Google Gemini AI",
        pageWidth / 2,
        260,
        { align: "center" }
    );

    doc.save(
    `${candidateName.replace(/\s+/g, "_")}_Cover_Letter_${targetCompany.replace(/\s+/g, "_")}.pdf`
);

});

// ===============================
// Gemini API Configuration
// ===============================

// API key is loaded from config.js
// Example:
// const GEMINI_API_KEY = "YOUR_API_KEY";

const GEMINI_API_URL =
`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${GEMINI_API_KEY}`;


// ===============================
// Generate Cover Letter
// ===============================

async function generateAICoverLetter(data, resumeText = "") {

    const prompt = `
You are an expert HR recruiter.

Generate a professional, ATS-friendly cover letter.

Candidate Name:
${data.name}

Job Role:
${data.role}

Target Company:
${data.company}

Key Skills:
${data.skills}

Resume:
${resumeText}

Requirements:

- Professional tone
- 3–5 paragraphs
- ATS Friendly
- Personalized
- No placeholders
- Return only the cover letter
`;

    try {

        const response = await fetch(GEMINI_API_URL, {

            method: "POST",

            headers: {
                "Content-Type": "application/json"
            },

            body: JSON.stringify({

                contents: [
                    {
                        parts: [
                            {
                                text: prompt
                            }
                        ]
                    }
                ]

            })

        });

        if (!response.ok) {

            throw new Error("Unable to connect to Gemini API.");

        }

        const result = await response.json();

        return (
            result.candidates?.[0]?.content?.parts?.[0]?.text ||
            "No cover letter generated."
        );

    }

    catch (error) {

        console.error("Gemini API Error:", error);

        return "Error: Unable to generate the cover letter. Please try again.";

    }

}

// ======================================
// PDF.js Worker Configuration
// ======================================

pdfjsLib.GlobalWorkerOptions.workerSrc =
    "https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.5.136/pdf.worker.min.js";

// ======================================
// Extract Text From Uploaded PDF
// ======================================

async function extractResumeText(file) {

    if (!file) {
        return "";
    }

    try {

        const arrayBuffer = await file.arrayBuffer();

        const pdf = await pdfjsLib.getDocument({
            data: arrayBuffer
        }).promise;

        let resumeText = "";

        for (let pageNumber = 1; pageNumber <= pdf.numPages; pageNumber++) {

            const page = await pdf.getPage(pageNumber);

            const content = await page.getTextContent();

            const pageText = content.items
                .map(item => item.str)
                .join(" ");

            resumeText += pageText + "\n\n";
        }

        return resumeText;

    } catch (error) {

        console.error("PDF Extraction Error:", error);

        return "";

    }

}